export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const GET_TODO = 'GET_TODO'
export const DONE = 'DONE'
export const TODO_ERROR = 'TODO_ERROR'
export const SET_ALERT = 'SET_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const LOAD_USER = 'LOAD_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

